apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
  labels:
    app: weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: nih13/weather-balloon:1.0.0
        ports:
        - containerPort: 4000
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: weather-secret
              key: api_key
        
---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  type: NodePort
  selector:
    app: weather
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30100